openapi: 3.0.3
info:
  title: AgentTrust Decision Service - Internal API
  version: 0.2.0
servers:
  - url: http://localhost:8083

paths:
  /internal/v1/decisions:
    post:
      summary: Compute deterministic decision (internal)
      description: |
        Internal API.

        Tenant context is derived by gateway (Host -> tenant mapping) and propagated to this service via X-Tenant-Id.
        This API does not accept tenantId in the request body.

        Observability headers (X-Correlation-Id, traceparent, tracestate) are propagated end-to-end when present.

        Digest support (Sprint 4): Content-Digest must use sha-256=:<base64>:.
      security:
        - ScopedTokenHeader: []
      parameters:
        - in: header
          name: X-Tenant-Id
          required: true
          schema:
            type: string
            minLength: 1
          description: Tenant identifier derived by gateway. Must not come from request body.

        - in: header
          name: Signature-Input
          required: true
          schema:
            type: string
          description: RFC 9421 Signature-Input header (edge-supplied; forwarded by gateway).

        - in: header
          name: Signature
          required: true
          schema:
            type: string
          description: RFC 9421 Signature header (edge-supplied; forwarded by gateway).

        - in: header
          name: Content-Digest
          required: true
          schema:
            type: string
          description: |
            HTTP Content-Digest header.

            Sprint 4 supports only: sha-256=:<base64>:
            Unsupported algorithms are rejected with 400 (DIGEST_UNSUPPORTED).

        - in: header
          name: Idempotency-Key
          required: true
          schema:
            type: string
            minLength: 16
            maxLength: 128
          description: |
            Idempotency key for safe retries and deduplication.

            For Sprint 4, method/path used in requestHash are external evaluate constants:
            method=POST, path=/v1/agent/decisions/evaluate.

        - in: header
          name: X-Correlation-Id
          required: false
          schema:
            type: string
          description: Optional correlation identifier for logs/traces.

        - in: header
          name: traceparent
          required: false
          schema:
            type: string
          description: Optional W3C Trace Context traceparent header.

        - in: header
          name: tracestate
          required: false
          schema:
            type: string
          description: Optional W3C Trace Context tracestate header.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DecisionEvaluateRequest"
      responses:
        "200":
          description: Decision computed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DecisionEvaluateResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "409":
          $ref: "#/components/responses/Conflict"

components:
  securitySchemes:
    ScopedTokenHeader:
      type: apiKey
      in: header
      name: X-Scoped-Token

  schemas:
    DecisionEvaluateRequest:
      type: object
      required: [action, amount, currency]
      properties:
        action:
          type: string
          description: Requested commerce action. MVP supports PURCHASE only.
          enum: [PURCHASE]
          example: PURCHASE
        amount:
          type: integer
          format: int64
          description: Minor units (e.g., cents). Must be >= 0.
          minimum: 0
          example: 1299
        currency:
          type: string
          description: ISO 4217 currency code (3-letter uppercase).
          pattern: "^[A-Z]{3}$"
          example: USD
        correlationId:
          type: string
          nullable: true
          description: Optional client correlation id for linking logs/traces across systems (not used for idempotency).
          example: corr_abc123
        checkoutReference:
          type: string
          nullable: true
          description: Non-tenant business reference (order/cart/checkout id). Not used for tenant resolution.
          example: order_9f2c1a

    DecisionEvaluateResponse:
      type: object
      required: [decision, decisionId]
      properties:
        decision:
          type: string
          enum: [ALLOW, CHALLENGE, DENY]
        decisionId:
          type: string
          example: dec_01HXYZ...
        tokenId:
          type: string
          nullable: true
          description: Token identifier (not the raw token).
        reasonCode:
          type: string
          nullable: true

    ProblemDetails:
      type: object
      required: [type, title, status]
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
          format: uri

        errorCode:
          type: string
          nullable: true
          description: Stable machine-readable error code.

        traceId:
          type: string
          nullable: true
          description: Trace identifier for server-side debugging.

        requestId:
          type: string
          nullable: true
          description: Server-generated request identifier if available.

        tenantId:
          type: string
          nullable: true
          description: Tenant id associated with the request when available.

        correlationId:
          type: string
          nullable: true
          description: Client correlation id if provided (request body correlationId or X-Correlation-Id).

        idempotencyKey:
          type: string
          nullable: true
          description: Echo of the Idempotency-Key header when provided.

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
    Unauthorized:
      description: Authentication failed
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
    Conflict:
      description: Idempotency conflict
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
